/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ipass;

import org.junit.Ignore;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

@Ignore
public class AppTest {
    @Test
    public void testSimple() {
        assertEquals("test", "test");
    }
}
