######################################################################
# Automatically generated by qmake (3.0) Mo. Dez. 19 12:21:28 2016
######################################################################

TEMPLATE = app
TARGET = PwdGenPro
QT += gui widgets
INCLUDEPATH += . /usr/include/cryptopp
LIBS += -Wl,-Bstatic -lcryptopp -Wl,-Bdynamic -lpthread

# Input
HEADERS += pwdGenPro.h
SOURCES += main.cpp pwdGenPro.cpp
